version: "3.8"

services:
  mm2-next:
    image: docker.io/ysukharenko/mm2-next:latest
    container_name: mm2-next
    restart: unless-stopped
    network_mode: host # Required for accessing dump1090 on local network
    ports:
      - "8082:8082" # Only used when not in host mode
    env_file: .env.docker
    environment:
      # Variables are loaded from .env.docker
      # You can override them here if needed
      - NODE_ENV=production
